server:
  port: 8081

spring:
  name: ssodemo
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: external-client
            client-secret: Vfs5H901d1EQjApwErFcQ7jkDzFiTPn9
            scope: openid,profile,email
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8081/login/oauth2/code/keycloak
        provider:
          keycloak:
            issuer-uri: http://0.0.0.0:8080/realms/external

